services:
  account-service:
    build: ./account-service
    container_name: account-service
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
    networks:
      - network

  db-postgres:
    image: postgres:17.5-alpine
    container_name: db-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-account-db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge