server:
  port: 8081
spring:
  application:
    name: account-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
  datasource:
    url: jdbc:postgresql://${TRANSACTION_SERVICE_DB_HOST:db-postgres}:${TRANSACTION_SERVICE_DB_PORT:5432}/${TRANSACTION_SERVICE_DB_NAME:account-db}
    username: ${TRANSACTION_SERVICE_DB_USERNAME:postgres}
    password: ${TRANSACTION_SERVICE_DB_PASSWORD:postgres123}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true