server:
  port: 8081
spring:
  application:
    name: account-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}  # Mudança aqui
  datasource:
    url: jdbc:postgresql://${DB_HOST:db-postgres}:${DB_PORT:5432}/${DB_NAME:account-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres123}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
