name: ci-account-service
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
on:
  push:
    branches: [ "main" ]
    paths:
      - 'account-service/**'
      - '.github/workflows/account-service.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'account-service/**'
      - '.github/workflows/account-service.yml'
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./account-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests with Maven Wrapper
        run: |
            chmod +x mvnw
            ./mvnw test -Dspring.profiles.active=test --batch-mode

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'account-service/target/surefire-reports/TEST-*.xml'

